version: '3.2'
services:
  backend1:
      container_name:  node-app1
      build: ./node-app
      ports:
          - "8081:8080"
  backend2:
      container_name: node-app2
      build: ./node-app
      ports:
          - "8082:8080"
  loadbalancer:
      container_name: nginx-lb
      build: ./loadbalancer
      ports:
          - "8080:80" 
      links:
          - backend1
          - backend2
